repos:
  # fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^dist/.*$
      - id: trailing-whitespace
        exclude: ^(dist/.*|.*\.(md|MD))$
      - id: mixed-line-ending
  # lint
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/tr8team/gotrade-pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: yamlfmt
        exclude: ^.*node_modules.*$
      - id: mdfmt
        exclude: ^(.*node_modules.*|Changelog.md)$
      - id: nixfmt
      - id: shfmt
      - id: jsonfmt
        exclude: ^.*node_modules.*$
      - id: dockerlint
      - id: nodelint
      - id: tslint
      - id: exec-enforce
        files: ^scripts.*\.sh$
      - id: releaser-enforce
      - id: action-docs-enforce
